version: '3.8'

services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - shared_network

  aes_fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aes_fe
    restart: always
    ports:
      - "3100:80"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
